[plugin]
repository = "https://github.com/Critical-Impact/AutoMountBGM.git"
owners = [ "Critical-Impact",]
project_path = ""
commit = "ea70ff765cc1bc1b0a438b6fe038dc73f782cc01"
changelog = "### Fixed\n- Support for 7.4"
version = "1.3.0.0"
