[plugin]
repository = "https://github.com/Critical-Impact/FantasyPlayer.git"
commit = "a90cad2388254bf946718be009668abbd328c5d6"
owners = [ "Critical-Impact",]
project_path = "FantasyPlayer"
version = "2.5.0.0"
changelog = "### Fixed\n- Support for 7.4"
