[plugin]
repository = "https://github.com/Critical-Impact/Tippy.git"
owners = [ "kalilistic", "Critical-Impact",]
project_path = "src/Tippy"
commit = "a3425dd8f685c4e802fa3728bec6ba6f15218127"
version = "1.14.0.0"
changelog = "### Fixed\n- Support for 7.4"
