[plugin]
repository = "https://github.com/Critical-Impact/AllaganItemSearch.git"
commit = "facf2b0f77a02f4907c09fed3826fef9fb85ea3c"
owners = [ "Critical-Impact",]
project_path = "AllaganItemSearch"
version = "1.2.0.0"
changelog = "### Fixed\n- Support for 7.4"
